input_path_cones: /mnt/d/isdc-stitcher/data/output/cone_detector/output.yaml
input_path_depth: /mnt/d/isdc-stitcher/data/output/stitcher/depth/
input_path_source_point: /mnt/d/isdc-stitcher/data/output/stitcher/source.yaml
output_path: /mnt/d/isdc-stitcher/data/output/path_planner/output/
