input_path: /mnt/d/isdc-stitcher/data/output/stitcher/rgb
model_path: /mnt/d/isdc-stitcher/models/depth_estimator/depth_anything_v2_base.pth
output_path: /mnt/d/isdc-stitcher/data/output/depth_estimator/
