input_path: /mnt/d/isdc-base-station/data/output/stitcher/rgb
model_path: /mnt/d/isdc-base-station/models/depth_estimator/depth_anything_v2_base.pth
output_path: /mnt/d/isdc-base-station/data/output/depth_estimator/
